apiVersion: v1
kind: Secret
metadata:
  name: {{ include "helm-chart.fullname" . }}-secret
  labels:
    {{- include "helm-chart.labels" . | nindent 4 }}
type: Opaque
stringData:
  MINIO_USER: {{ .Values.secrets.minioUser }}
  MINIO_PASSWORD: {{ .Values.secrets.minioPassword }}
  POSTGRES_USER: {{ .Values.secrets.postgresUser }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgresPassword }}